added card markup and style, added grid
Valeriia-Trytiak/project_01_Taste_Masters_Team pull request #10
Opened 2023-09-15 17:43 UTC by Agmund2002

2023-09-15 19:56 UTC, Valeriia-Trytiak requested changes
Трохи виправити і добре буде. Так як нема карток, не можу зрозуміти чи спрацює сітка як треба. Бо зараз розміри карток не відповідають макету. Та мені капець як не подобається твое позицінування блоку з зірками. МОже щось вигадаємо краще

2023-09-15 19:56 UTC, Valeriia-Trytiak commented on src/partials/cards-section.html
> +    <img class="card-img" src="https://i.obozrevatel.com/food/recipemain/2018/12/29/item4162.jpg?size=636x424" alt="imgas">
додай атрибут лоадинг лейзи

2023-09-15 19:56 UTC, Valeriia-Trytiak commented on src/css/cards-section.css
> +    line-height: 16px;
перерахуй у відношені 16/12

2023-09-15 19:56 UTC, Valeriia-Trytiak commented on src/css/cards-section.css
> +    margin-top: 1px;
мені дуже не подабається твоє позицінування маржинами. Але я ще не придумала кращий варіант

2023-09-16 12:38 UTC, Valeriia-Trytiak commented on src/css/cards-section.css
> +    line-height: calc(16/12);
та міг би просто числом написати. Це я тобі казала про відношення та дала приклад, щоб ти зрозумів звідки число1,33 =))

2023-09-16 12:50 UTC, Valeriia-Trytiak requested changes
повидись маржин-боттом у .card-list -вони дублюються та вони не потрібні на списку, прибери. Відстань між картками вираховується автоматично (із кастомних стилей, ну ти в курсі)

2023-09-16 12:58 UTC, Agmund2002 commented
> повидись маржин-боттом у .card-list -вони дублюються та вони не потрібні на списку, прибери. Відстань між картками вираховується автоматично (із кастомних стилей, ну ти в курсі)

2023-09-16 13:24 UTC, Valeriia-Trytiak approved these changes

2023-09-16 13:24 UTC, merged