Modal-rating_first commit
Valeriia-Trytiak/project_01_Taste_Masters_Team pull request #5
Opened 2023-09-14 18:48 UTC by Cajamarquina

2023-09-14 21:11 UTC, Valeriia-Trytiak requested changes
залишила помітки не по всіх багаг. Щось повторюється. Щось буде змінюватися після внесенних змін.

2023-09-14 21:11 UTC, Valeriia-Trytiak commented on src/css/modal-rating.css
> +.visually-hidden {
це перетягну до основного файлу стилів як дефолтні

2023-09-14 21:11 UTC, Valeriia-Trytiak commented on src/css/modal-rating.css
> +    transition: opacity 250ms cubic-bezier(0.4, 0, 0.2, 1), visibility 250ms cubic-bezier(0.4, 0, 0.2, 1);
кубик є у root

2023-09-14 21:11 UTC, Valeriia-Trytiak commented on src/css/modal-rating.css
> +@media screen and (min-width: 1158px) {
в нас інша точка зламу

2023-09-14 21:11 UTC, Valeriia-Trytiak commented on src/css/modal-rating.css
> +    background-color: var(--bg-cl-light-theme);
там білий колір по макету

2023-09-14 21:11 UTC, Valeriia-Trytiak commented on src/css/modal-rating.css
> +        font-style: normal;
зайве

2023-09-14 21:11 UTC, Valeriia-Trytiak commented on src/partials/modal-rating.html
> +<button type=submit class="rating-send"><p class="rating-btn-text">Send</p></button>
навіщо тут тег <p>?  Send прописується у тезі button

2023-09-15 06:31 UTC, Valeriia-Trytiak requested changes
Передивись стилі, розміри модального вікна не відповідають макету (на точках зламу проблема з висотою). Також Трохи 'причеши' свій код, його складно читати. Селектори повторюються.

2023-09-15 06:31 UTC, Valeriia-Trytiak commented on src/partials/modal-rating.html
> +<i class="rating-star">
будь-ласка аргументуй використання текстового тегу і для іконки. Зроби списком.

2023-09-15 06:53 UTC, Cajamarquina commented on src/partials/modal-rating.html
> +<i class="rating-star">
"Також Трохи 'причеши' свій код, його складно читати. Селектори повторюються." -  Поясни, я не розумію. Наприклад?
Хочеш списком зірки, я зроблю. Якщо погуглити, то усі приклади зіркового рейтингу написані <i>.

2023-09-15 06:59 UTC, Valeriia-Trytiak commented on src/partials/modal-rating.html
> +<i class="rating-star">
стосовно групування властивостей. Зараз я тобі надішлю голосове, ок?

2023-09-15 09:35 UTC, Valeriia-Trytiak requested changes
1. Подивись на 374рх, 768рх щось з свг, вона гіганська 
2.  font-weight: 500 додати на .rating-result;
3. gap:2 додати на .rating-stars-container;
4.  додати верхій та нижній паддінг 14 рх на .rating-form-input
5. я не можу ввести емаил в интут;
6.

2023-09-15 09:35 UTC, Valeriia-Trytiak commented on src/css/modal-rating.css
> + @media screen and (min-width: 768px){
спробуй прописати 767.9

2023-09-15 09:35 UTC, Valeriia-Trytiak commented on src/css/modal-rating.css
> +@media screen and (min-width: 375px) and (max-width: 767px){
спробуй 767.9

2023-09-15 10:20 UTC, Valeriia-Trytiak approved these changes
супер!

2023-09-15 10:20 UTC, merged